server.port: 9091

spring:
  jackson:
    default-property-inclusion: non_null
    serialization.write-dates-as-timestamps: false
    deserialization.fail-on-unknown-properties: true
  cloud:
    stream:
      binders:
        kafkaJson:
          type: 'kafka'
          defaultCandidate: true
          environment:
            spring:
              kafka:
                consumer:
                  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
                  value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
                producer:
                  client.id: '${spring.application.name}'
                  key-serializer: org.apache.kafka.common.serialization.StringSerializer
                  value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        kafkaAvro:
          type: 'kafka'
          environment:
            spring:
              kafka:
                properties:
                  schema.registry.url: http://k-tools.stg.pagseguro.intranet:8081
                  specific.avro.reader: true
                consumer:
                  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
                  value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
                producer:
                  client.id: '${spring.application.name}'
                  key-serializer: org.apache.kafka.common.serialization.StringSerializer
                  value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      bindings:
        multiple-card-authorizer-transactions-out-0:
          destination: 'cmd.dsr.bank.cards.multiplecard.transactions'
          content-type: 'application/json'
        interactive-campaign-user-accept-campaign-out-0:
          binder: kafkaAvro
          destination: 'cmd.dsr.customer.communication.user-accept-interactive-campaign'
          content-type: 'application/*+avro'
          producer:
            useNativeEncoding: true
      kafka:
        binder:
          brokers: broker1-aws2.stg.pagseguro.intranet:9093, broker2-aws2.stg.pagseguro.intranet:9093,
            broker3-aws2.stg.pagseguro.intranet:9093
          configuration:
            security.protocol: SSL
            ssl.truststore.location: ${broker-certificate.local.truststore}
            ssl.truststore.password: ${broker-certificate.password.truststore}
            ssl.keystore.location: ${broker-certificate.local.keystore}
            ssl.keystore.password: ${broker-certificate.password.keystore}
            ssl.keymanager.algorithm: PKIX
            ssl.trustmanager.algorithm: PKIX
            ssl.keystore.type: pkcs12
            ssl.truststore.type: pkcs12
            ssl.enabled.protocols: TLSv1.2
            auto-create-topics: true